applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),
    path(
        'listar-todo-empleado/',
        views.ListAllEmpleado.as_view(),
        name='empleado_all'
        ),
    path(
        'list-by-area/<shorname>/',
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
        ),
    path(
        'list-empleados-admin/',
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
        ),
    path('list-by-job/<job>/', views.ListEmpleadoByJob.as_view()),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>/',
         views.EmpleadoDetailView.as_view(),
         name='empleado_detail'
         ),
    path(
        'add-empleado/',
         views.EmpleadoCreateView.as_view(),
         name='empleado_add'
         ),
    path(
        'success/',
         views.SuccessView.as_view(),
          name='correcto'
    ),
    path(
        'update-empleado/<pk>/',
         views.EmpleadoUpdateView.as_view(),
          name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>/',
         views.EmpleadoDeleteView.as_view(),
          name='eliminar_empleado'
    ),
]

empleados/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos las urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.persona.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField

# Create your models here.
class Habilidades(models.Model):
    habilidad = models.CharField("Habilidad", max_length=50)

    class Meta:
        verbose_name = "Habilidad"
        verbose_name_plural = "Habilidades Empleados"
    
    def __str__(self): #Texto concatenado con formato
        return f"{str(self.id)}-{self.habilidad}"


class Empleado(models.Model):
    """ Modelo para tabla empleado """

    JOB_CHOICES = (
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'INFORMATICO'),
        ('4', 'OTRO')
    )
    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField(
        'Nombres completos',
        max_length=120,
        blank=True
    )
    job = models.CharField('Trabajo', max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="empleados", blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()

    class Meta:
        verbose_name = "Empleado"
        verbose_name_plural = "Empleados de la empresa"
        ordering = ["first_name", "last_name"]
        unique_together = ("first_name", "departamento")

    def __str__(self): #Texto concatenado con formato
        return f"{str(self.id)}-{self.first_name}-{self.last_name}"

applications/persona/forms.py
from django import forms

from .models import Empleado

class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
            }

applications/persona/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView,
)
# models
from .models import Empleado
# forms
from .forms import EmpleadoForm
# 1- lista todos los empleados de la empresa
# 2- listar todos los empleados que pertenecen a un area de la empresa
# 3- listar empleados por trabajo
# 4- listar los empleados por palabra clave
# 5- listar habilidades de un empleado

class InicioView(TemplateView):
    """ vista que carga la pagina de inicio"""
    template_name = 'inicio.html'


class ListAllEmpleado(ListView):
    template_name = 'persona/list_all.html'
    paginate_by = 4
    ordering = 'first_name'
    context_object_name = 'empleado'

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", "")
        lista = Empleado.objects.filter(
            first_name__icontains=palabra_clave
        )
        return lista


class ListByAreaEmpleado(ListView):
    """ Lista empleados de un area """
    template_name = 'persona/list_by_area.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        #El codigo que yo quiera
        area = self.kwargs["shorname"]
        lista = Empleado.objects.filter(
            departamento__shor_name=area
    )
        return lista 


class ListaEmpleadosAdmin(ListView):
    template_name = 'persona/lista_empleados.html'
    paginate_by = 10
    ordering = 'first_name'
    context_object_name = 'empleado'
    model = Empleado
    

class ListEmpleadoByJob(ListView):
    """ Lista empleados por trabajo """
    template_name = 'persona/list_by_job.html'

    def get_queryset(self):
        #El codigo que yo quiera
        area = self.kwargs["job"]
        lista = Empleado.objects.filter(
            job=area 
    )
        return lista 


class ListEmpleadosByKword(ListView):
    """ Lista empleados por palabra clave """
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        print("********************")
        palabra_clave = self.request.GET.get("kword", "")
        lista = Empleado.objects.filter(
            first_name=palabra_clave
    )
        return lista


class ListHabilidadesEmpleado(ListView):
    template_name = 'persona/habilidades.html'
    context_object_name = "habilidades"

    def get_queryset(self):
        employee_id = self.request.GET.get("employee_id", 1)
        empleado = Empleado.objects.get(id=employee_id)
        return empleado.habilidades.all()


class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"

    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        #todo un proceso
        context["titulo"] =  "Empleado del mes"
        return context


class SuccessView(TemplateView):
    template_name = "persona/success.html"


class EmpleadoCreateView(CreateView):
    template_name = "persona/add.html"
    model = Empleado
    form_class = EmpleadoForm
    success_url = reverse_lazy('persona_app:empleados_admin')

    def form_valid(self, form):
        #logica del codigo/proceso
        empleado = form.save(commit=False)
        empleado.full_name = f"{empleado.first_name} {empleado.last_name}"
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    template_name = "persona/update.html"
    model = Empleado
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
    ]
    success_url = reverse_lazy('persona_app:empleados_admin')

    def post(self, request, *args, **kwargs):
        self.objects = self.get_object()
        print('**********METODO POST**********')
        print('====================')
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        #logica del codigo/proceso
        print('**********METODO form valid**********')
        print('********************')
        return super(EmpleadoUpdateView, self).form_valid(form)
        
    
class EmpleadoDeleteView(DeleteView):
    template_name = "persona/delete.html"
    model = Empleado
    
    success_url = reverse_lazy('persona_app:empleados_admin')

templates/persona/add.html
{% extends 'base.html' %}

{% block title %}
    Registar Empleado
{% endblock title %}
    
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Empleado</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="mutipart/form-data" >{% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombres:
                  {{ form.first_name }}
                </label>
              </div>
              <div class="medium-6 cell">
                <label>Apellidos:
                  {{ form.last_name }}
                </label>
              </div>
              <div class="medium-6 cell">
                <label>Trabajo:
                  {{ form.job }}
                </label>
              </div>
              <div class="medium-6 cell">
                <label>Departamento:
                  {{ form.departamento }}
                </label>
              </div>
              <div class="medium-12 cell">
                <label>Habilidades Extra:
                  {{ form.habilidades }}
                </label>
              </div>
              <div class="medium-12 cell">
                <label>Foto:
                  {{ form.avatar }}
                </label>
              </div>
              <div class="medium-12 cell">
                <button type="submit" class="button success">Guardar</button>
              </div>
        </form>
    </div>
</div>

{% endblock content %}
<h1>Registar Persona</h1>

<form method="POST">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Agregar</button>
</form>

templates/persona/by_kword.html
<h1>Buscar empleado por palabra clave</h1>
<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="ingrese nombre aqui">
    <button type="submit">Buscar</button>
</form>

<h3>Lista resultados</h3>
<ul>
    
    {% for e in empleados %}
        <li>{{e}}</li>
    {% endfor %}
        
</ul>

templates/persona/delete.html
{% extends 'base.html' %}

{% block title %}
    Eliminar Empleado
{% endblock title %}

{% block content %}
  {% include 'includes/header.html' %}  
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar empleado: {{ object.first_name }}</h1>

        <form class='cell' method="POST">{% csrf_token %}
            <div class="callout secondary">
                <h5>¿Desea eliminar este empleado?</h5>
                <button type="submit" class="alert button">Confirmar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/persona/detail_empleado.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{ object.full_name }}
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x grid-margin-x aling-center">
        <div class="cell large-4 card" style="width: 300px; margin-top: 10px">
            <div class="card-divider">
              {{ empleado.get_job_display }}
            </div>
            {% if empleado.avatar %}
                <img src="{{ empleado.avatar.url }}">
            {% else %}
                <img src="{% static 'empleados/tommy.jpeg' %}">
            {% endif %}
            <div class="card-section">
              <h4>{{ empleado.first_name }}</h4>
              <p>{{ empleado.last_name }}</p>
              <p>{{ empleado.departamento.shor_name }}</p>
              <p><span class="label">Habilidades:</span></p>
              <ul class="vertical menu">
                    {% for h in empleado.habilidades.all %}
                         <li>{{ h.habilidad }}</li>
                    {% endfor %}  
              </ul>
            </div>
        </div>
    </div>
</div>

{% endblock content %}
<h1>Detalle de un empleado {{ titulo }}</h1>
{{ object }}   # o {{ empleado }}

<h3>Todos los datos:</h3>
<p>{{ empleado.first_name }}</p>
<p>{{ empleado.last_name }}</p>
<p>{{ empleado.departamento }}</p>
<p>{{ empleado.habilidades }}</p>

templates/persona/habilidades.html
<h1>Habilidades de empleado</h1>
<form method="GET">
    <input type="number" id="kword" name="employee_id" placeholder="ingrese nombre aqui">
    <button type="submit">Buscar</button>
</form>

<ul>
    
    {% for h in habilidades %}
        <li>{{ h }}</li>
    {% endfor %}
        
</ul>

templates/persona/list_all.html
{% extends 'base.html' %}

{% block content %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %} 
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="Buscar Empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in empleado %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.departamento }}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div clas="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>
                    {% endif %}
                        
                    {% for pagina in paginator.page_range %}

                    
                    {% ifequal pagina page_obj.number %}
                    <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li> 
                    {% else %}
                    <li class=""><a href="?page={{pagina}}">{{ pagina }}</a></li>
                        
                    {% endifequal %}
                    {% endfor %}
                        
                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li>
                    {% endif %}
            </nav> 
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/persona/list_by_area.html
{% extends 'base.html' %}

{% block tittle %}
    lista empleados por departamento
{% endblock tittle %}
    
{% block content %}
    {% include 'includes/header.html' %}
    <div lass="grid-container">
        <div class="grid-x">
            <div class="cell">Empleados por area:</div>
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCION</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for e in empleados %}
                        <tr>
                            <td>{{ e.id }}</td>
                            <td>{{ e.first_name }}</td>
                            <td>{{ e.last_name }}</td>
                            <td>{{ e.departamento }}</td>
                            <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}
    

<h1>Lista empleados por departamento</h1>

<ul>
    
    {% for e in object_list %}
       <li>{{ e }}</li>
    {% endfor %}
        
</ul>

templates/persona/list_by_job.html
<h1>Lista empleados por trabajo</h1>

<ul>
    
    {% for e in object_list %}
       <li>{{ e }}</li>
    {% endfor %}
        
</ul>

templates/persona/lista_empleados.html
{% extends 'base.html' %}

{% block content %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                    <th width="200">ID</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in empleado %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.departamento }}</td>
                        <td>
                            <a class="button success" href="{% url 'persona_app:modificar_empleado' e.id %}">Editar</a>
                        </td>
                        <td>
                            <a class="button alert" href="{% url 'persona_app:eliminar_empleado' e.id %}">Eliminar</a>
                        </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div clas="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="pagination-previous">
                        <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>
                    {% endif %}
                        
                    {% for pagina in paginator.page_range %}

                    
                    {% ifequal pagina page_obj.number %}
                    <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li> 
                    {% else %}
                    <li class=""><a href="?page={{pagina}}">{{ pagina }}</a></li>
                        
                    {% endifequal %}
                    {% endfor %}
                        
                    {% if page_obj.has_next %}
                    <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                    </li>
                    {% endif %}
            </nav> 
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/persona/success.html
<h1>Felicitaciones, se guardo correctamente el empleado</h1>

templates/persona/update.html
{% extends 'base.html' %}


{% block title %}
    Editar Empleado
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Modificar Empleado
        </h1>
        <div class="cell">
            <form class='grid-x grid-margin-x' method="POST">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres:
                        {{ form.first_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellidos:
                        {{ form.last_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo:
                        {{ form.job }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Area:
                        {{ form.departamento }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Habilidades Extra:
                        {{ form.habilidades }}
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="success button">Guardar</button>
                </div>
            </form> 
        </div>
    </div>
</div>

{% endblock content %}