applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "departamento_app"

urlpatterns = [
    path(
        'departament-list/',
     views.DepartamentListView.as_view(),
      name='departament_list'),
    path(
        'new-departament/',
        views.NewDepartamentView.as_view(),
        name='new_departament'
        ),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),
    path(
        'listar-todo-empleado/',
        views.ListAllEmpleado.as_view(),
        name='empleado_all'
        ),
    path(
        'list-by-area/<shorname>/',
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
        ),
    path(
        'list-empleados-admin/',
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
        ),
    path('list-by-job/<job>/', views.ListEmpleadoByJob.as_view()),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>/',
         views.EmpleadoDetailView.as_view(),
         name='empleado_detail'
         ),
    path(
        'add-empleado/',
         views.EmpleadoCreateView.as_view(),
         name='empleado_add'
         ),
    path(
        'success/',
         views.SuccessView.as_view(),
          name='correcto'
    ),
    path(
        'update-empleado/<pk>/',
         views.EmpleadoUpdateView.as_view(),
          name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>/',
         views.EmpleadoDeleteView.as_view(),
          name='eliminar_empleado'
    ),
]

empleados/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos las urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.persona.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li>
          <a href="{% url 'persona_app:empleado_all' %}">Listar</a>
        </li>
        <li><a href="{% url 'departamento_app:departament_list' %}">Departamentos</a></li>
        <li><a href="{% url 'persona_app:empleados_admin' %}">Administrar</a></li>
        <li><a href="{% url 'departamento_app:new_departament' %}">Nuevo Departamento</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar empleado"></li>
        <li><a href="{% url 'persona_app:empleado_add' %}" class="button">Registrar Nuevo</a></li>
      </ul>
    </div>
</div>