applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "persona_app"

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
    ),
    path(
        'listar-todo-empleado/',
        views.ListAllEmpleado.as_view(),
        name='empleado_all'
        ),
    path(
        'list-by-area/<shorname>/',
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
        ),
    path(
        'list-empleados-admin/',
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
        ),
    path('list-by-job/<job>/', views.ListEmpleadoByJob.as_view()),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>/',
         views.EmpleadoDetailView.as_view(),
         name='empleado_detail'
         ),
    path(
        'add-empleado/',
         views.EmpleadoCreateView.as_view(),
         name='empleado_add'
         ),
    path(
        'success/',
         views.SuccessView.as_view(),
          name='correcto'
    ),
    path(
        'update-empleado/<pk>/',
         views.EmpleadoUpdateView.as_view(),
          name='modificar_empleado'
    ),
    path(
        'delete-empleado/<pk>/',
         views.EmpleadoDeleteView.as_view(),
          name='eliminar_empleado'
    ),
]

empleados/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos las urls de la app departamento
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.persona.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/departament/lista.html
{% extends 'base.html' %}


{% block tittle %}
    Lista departamentos
{% endblock tittle %}


{% block content %}
    {% include 'includes/header.html' %}
    
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        {% for departamento in departamentos %}
                        <tr>
                            <td>{{ departamento.name }}</td>
                            <td>{{ departamento.shor_name }}</td>
                            <td>
                                <a class="button warning" href="{% url 'persona_app:empleados_area' departamento.shor_name %}">Ver Empleados</a>
                            </td>
                        </tr> 
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}
    

templates/departament/new_departament.html
{% extends 'base.html' %}

{% block title %}
    Registar Departamento
{% endblock title %}
    
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Departamento</h1>
        <form class="cell callout grid-x grid-margin-x" method="POST">{% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombres:
                    {{ form.nombre }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>apellidos:
                    {{ form.nombre }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>departamento:
                    {{ form.nombre }}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>shorname:
                    {{ form.nombre }}
                </label>
            </div>
            <div class="medium-12 cell">
                <button type="submit" class="button" >Guardar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}